### ISSUE TITLE
我相信最后会变成莆田医院大众点评网

### ISSUE THREAD

**Issue by aqiansunboy** [shixinzhang/BlackheartedHospitalApp#1]

**Comment by shixinzhang** [comment]
你这个想法很不错啊~(≧▽≦)/~

**Comment by aqiansunboy** [comment]
楼主，我是在嘲讽，没有听出来吗？是非功过，我们没必要一棒子打死，更没必要参与跟风。媒体的报道本身就可能不怀好意，谁能知道这事儿的背后推手是何居心。出发点是好的，但小心不要把自己变成为另一种恶的参与者。

**Comment by shixinzhang** [comment]
恩，谢谢你的提醒，我也考虑到了，所以停止更新了。
![截图](https://cloud.githubusercontent.com/assets/17017832/15065479/b1de8d18-1392-11e6-896d-a3e814f14293.jpg)
