### ISSUE TITLE
ToolBar 应该放置一个返回的按钮；图标的清晰度不够

### ISSUE THREAD

**Issue by mizhoux** [shixinzhang/BlackheartedHospitalApp#2]
首先得表扬你这 App 做的不错（主要是指这个 App 的意义）
1、ToolBar 点击最左边的位置可以返回（说明你功能已经实现了），但是是否应该加上一个返回的示意按钮呢？主要是有些 Android 手机并没有返回键（比如我的），有个返回的图标会让我们这种手机体验更好。示例图片：
![2016050601](https://cloud.githubusercontent.com/assets/15724596/15076301/936f58d2-13db-11e6-9598-1bb084f92933.png)

2、还有就是 App 图标的清晰度不够，希望可以改善。
![2016050602](https://cloud.githubusercontent.com/assets/15724596/15076516/ad92277a-13dc-11e6-846d-68041c2dbc5f.png)

**Comment by shixinzhang** [comment]
I give up this project because of some reasons, sorry to close your issue.
